apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credential
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: ghcr-credential
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: /GHCR_USERNAME
    - secretKey: password
      remoteRef:
        key: /GHCR_TOKEN
