---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: infisical-universal-auth
  namespace: norriswu0-dev
spec:
  encryptedData:
    client_id: AgCVQyerq0z3SYIXh8ZnSTdnT9uPQCfBtO5AqnWx8kyhygf0VZBoFoEZPG00jhLY3Et2tGNkuEaWotMg9omlYvogRTpPSoQejt24tx3ZcRPyTTzLGxsAf8Dtn98jHghUj6j3dCKEI6kqz9WkqU+IA4mDP4prTegfZjWSDYK8V64t4vBy1vPB7C3nA2YxoYTwi+sSiv9n4NwExeQSfZL8PujAphPq8Pzny3Z5BNXNCEyJoBhqpBi+uqR7FW7ol7+ntuwILq9hDmkTbMi34wjhVCZP8ZFa4njFw58XnA4SJLvnpL0s+sZlNlhFQpxi48qs1lVU97kxelRBmS8oMfIX6TrO/GYz+XYpKShLxi+nwrELM1FpgRgjfb2nQt1bqTdnEj/wRpMlLNQPcUeFrL916nzkS0Yct++A0U7m0CZV0j47Onrtwv6DbvBdNMl4ZA/+UmKR8dWWWQTksppQfJRrtjPeOsXyHbznArLV3mjafJtJLfIgKSiOsf/V+N6Ca1AL1KCozfTFuyvqQnwitFSc7cqXUiqira0IEwXdDljFu5o7zSN5Kk0Dke8j5oCg6FWigxwBhc9xIE9nZtfUEEtkSrQg8ky568nOITiJ8WSAOk1XTRUTAj2YqV+YmFDH+J3pNmHBf4vAl5z3VnNXBtqNvdCmjQv2ObpDAowzIEm+xZDMuiH2/18tDiFxWVFSzfADP+e6z8IhqYzZKzr0ioAUJYFamOQZBRfrIDAXR6UUubgTQ43wOxI=
    client_secret: AgA7i3ofm//VRBCb+ZpMg1RtUxwDuN0Ozy7lBPqacrnvXA0mfTx0TJwE9XJxPuR5CKvW1s/Ng7JRiUqwRFWK19emARxvNlDAgO7aqeTyq5925ISrbQj5Vi9svKarQkl8kNsmi7XdbPvQogS/OJ3i8l85XkGiyHIH2TOl30O0XG8io2VmnPAXEXj8fPLWeZz3f/qWoLLTXWx8ExNcsEDLbwS57JZzA5rQ8EkmHRSNlIExRPUyT37dX0uyzIqwgSimbPwluGjP1KyQ3cW17XIgqwZjIE28E2f9BqmOocqIbAHFk4S6SAABxociRC0rwRU3FYoKzS49vDyPdWu7hur48Whc9QgQkEHDTTiO+KpBnbWRD6Xf83fN1SqewT/xHOYIDPbOqdeluJb2KJQpASPLKreB3WHtgZBfwxgOrXPpU9S6wVZ7qVMfqNuTO0lmulzJyZAA46HY55nx/Yjlg/zLuCqO9tosEZT8cd4uLWE4t4WxyNYf4oBCcosRSRkBmnqSlIrmdtDoL6v/pUx0GyBygSW7R6AqRJeqVDn8GGJGXVNuviC/Qdy0GNnbojfrprfeijOkccXiqo0+tiOOznLUymnysIARqJYC/+YFOrzNcsVAReNqBrNZ2TyQn8bOKDZ9bYWwdEjW1DUqT8zl7RUC/1auZZarbZhbfK18l6W6915quzVlTEPQ5E/5c5+UlETloymveUdQRW7345iIzorfmzneOtXcThETfXk5FsqNHvw7+nInMZ0Did0Ln7AkpxqBGGol7xhquHmZuAx1cCUbZ6ZT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: infisical-universal-auth
      namespace: norriswu0-dev
