---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-universal-auth
  namespace: norriswu0
spec:
  encryptedData:
    clientId: AgBCCSRee1iC4wWCzQOsIFFdHnWPXd4C9cu0U9ct+jGkoKjh0XM8x6kGE7E0H9Iy6ETHiHv7Wb4xKyDbxHDLrOO9maPlt1q1rMh7NdckBUvBDqQmRPK84u2BmCSnSvOqBv22ksuWuemWfPrbnQO3IzlfGTiZMf38+kMM79lWgpNCSCTgS3LiWTEqSwbtHRVjOEonQAfSiqa0Q7zdyA5ahfG+rmupdRFyIXyXzvzb+nVSIcHq42x1iOUZ1dNoxtGj2+Q6XIX8K1l+hXK8q+tqPjWbrhKZvDLztBkPD2VuQEWtR2XWfL516oNwW8qUFf32ZwP24CEbXKl+cmAVN1iTvuU7QDyJVe71SgLDjKMqOgFBLKQP3JSqCkCyQFe5rvhs05ewxUdSdOZeexwQmsGH8X8ZZb1jlcqfaxnKe094puiKX4oCrBfZKZBHgeJhfZVwigm1kSSe6s4htzdXtXOmTmRTREC+s5deuAswYu+swoktz+C9MirEI0rPg9XSbL6FZIprYm3gIR6RAJtsjkq4gMhs6EdltlFzub3wbtLzLUeqZQJ+PPgW2V/Av3aBvHpWRjzCn2MOyvZQU3D9EFL/wDnwF5wZB4tk/wCCvfeVjC6+Kim7if/sQDJ93Kntl/mCl9DYkJgbkxcE53Re9i88/YaGO9WXaSRaLGnUzferJ/VtViwCt7mdPijoDiXF+n7oNLqGu0ghXsC767mepaydd6EBPXkyAelZ85efaRrdm8s7CRkrlwg=
    clientSecret: AgBbV2Cb+xYbajSjfIT0y0ZKFFTt96sZuRISjoE/cZO5Jw+ydpqGOJsu0RGI/E/hx6+3zVtPx6uILL2m6bBzp93yWrUMVcrQsJ9E1s3b8wi/nybh49QiLap5GRD/YUUsG3fCKER5KlVR6WYIeTYeUtfiNSSfGXg15S2L02CHvRbYOy3TBVat540pdjAJeitvd7WaP4g4A+2otYLhWFdEHGGsTOKBCYABGVUl4ILAZ9rSX1tSNZ3m7knfPn092J7yFKCwn+Zaj8fU+3mv5Pr4yI3PrVojwq3DQYRRAH+JN1NlGtdvKEq2Os9K6w9Tj73acZJ2f6YQJ7I1hTkc7NW55yEIVbwIEeKmu8VdHLqJeULAwvASEhmn+YKwVCVy5NA82WSxCC96ggnFzzeMgKeh35h9BUM6/zK+TWdpYKHvn1nTnKFSMtGnWh6L1SxLTn3wIM8kwocgs5fsOfw4D+QV3fSlFQi0pl0Pmths4bqHKNHypmGYrqqfnlL9SjZA71uVBfnoT6YvvazMoiusjNgiMc6mFgMNGO6gc++BO5TzfTkYB67deazE/QVVp+iYXLJF31KtytNOo1SmSRpVzvKInz8MBWeQAJzjLCgSuVRPaKXfFlL46TUhWnfidJ7lbnDc5rvN8oDsGyvshtOAJqaa3zyCoJ5WrmFEMfYs4xUImkAdJmSD5ZjMbwJi60MMRGdLqP7YFe63N7Oi2n1DlY6wSvvO27bcY9WHqFkjXn9RXTBQlTTDVLB1WVsi7BJVR4jaHgB67d9snA0bJqdgPf/UAv98
  template:
    metadata:
      name: infisical-universal-auth
      namespace: norriswu0
    type: Opaque
