apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: norriswu0-secret-store
  namespace: norriswu0
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-universal-auth
            namespace: norriswu0
            key: clientId
          clientSecret:
            name: infisical-universal-auth
            namespace: norriswu0
            key: clientSecret
      secretsScope:
        projectSlug: norriswu0-2c-qx
        environmentSlug: prod
        secretsPath: /
        recursive: true
