apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norriswu0-prod

resources:
  - ../../base
  - httproute.yaml

images:
  - name: ghcr.io/norriswu0/me
    newTag: 62f713dff8a463aa3f04001a8aa28adebf888d7c
