apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yuvomi-secrets
  namespace: norriswu0
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: ClusterSecretStore
  target:
    name: yuvomi-secrets
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /yuvomi/SESSION_SECRET
    - secretKey: DB_ENCRYPTION_KEY
      remoteRef:
        key: /yuvomi/DB_ENCRYPTION_KEY
