---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: infisical-universal-auth
  namespace: norriswu0-prod
spec:
  encryptedData:
    client_id: AgBnuJAPGHdz5kyW/RCl1SH7T3xpaLyZ4T5RWD8HPLZChTaJlHbgxAlI6GFmzkWkQ3dgUvybifklWtRlEUMSudDLDvMh9kMoK9BwjYHxJNRLjy2/9Fg4SlNmSh3M24Alyyozbwx/1Nd8u9kSsArxM/OUEttrNkfROKQ7ruM/ZoXJzBncG0E+NB4mzu4W2F5/9Px4I9ojBmP3JgliicfC6Z94r2Lupflu3p+OvBy4mIJ+JhdPb6hcel0+grApXqajVcuHhenWk9D9bzSUpE9qbaP9fVaL5iSKse2zrlIt7CbZMEYtt2wV/9xPeoz/zFpj39MOqwaf/Ed6dkWs+gleP/0G2VRHnwYlQQ5ln4i7wcYegAVfxYOTFcBEjG4GmlB6kZWd6TUyxo6aF38ZfX04GwC3US/sCYALbgcpGeLC3mfp6ZJdwrr2zcQwE7eD9T2Eh+I9m6Tnnw8LozV9HckZAklV9pMs1qP7Vy9YawghI1n7MR7xyohKZrBMsN2s+21xnFQECb8vp3tAyOhP0+y5LowYI+504M1op5aJlZIeHUKnqUROWsP6joZWrRatbN6vVnqme5dR6h8dCq12eJ4kIFsWIAsl0nMZ6W7CQuFMXqKBCdKyDZVLpKTTqNdl2jvoziifngU6PSSjYQdH3dyunG8CBhxVExq0sjsPlw6FnkBhVtPFoI60SZeh7oSW8VFmlXZiqIvsbyN6B6SN56ETb9FL5Jaeffbz81UGLdjn+7hA/V9JdpY=
    client_secret: AgB89LPDxvgGd5LSsTUjsJ0tICJiT2IKEzO5mlaaPg2tQBm9osZ+EYND++cHCrHtb3jqYnJuJSHWv1nKH8TU8TF8D39U5u0ZYpSRGB1AjofvnppGjAa8s1wT3qG1V1vOWD/LjvgrRHTbT2DdMuAgRWqV8oJWOT13kjaL4Qd3oeTFLBk2+SpJwdOjvpkyxEYJZHY5QrCZ2dAshcJ5t1lAI/t3RjTdkVyCqRsOH0lr1c7KVMkEc77/nqWMYTvkaBEmRov2UjkESKsdAX/8wCHZO5vaKAR+ZvagDpeRszOScHQ1cacK4iTdtq3RIxp3F0NDrT1TA0UC7TSb2WuZMI71XsMjKHEpE6vwsWVlHTYWAtJu28qtDGCkaFd03lMuc3Pc/2YZQGOP3PE7ID90BQFbsIagxuMvk3AJTenWe4XuBpJYYI4qKsyUzFlq7EkHJ6NHJMthtWx6E5zOXkKA4m+PGvCwWEbMOEhJQWoeBTKdXIrV81B3qMr6wXMgiwWO0IplUL11S3PNjaywVdac6YOjYUFRjTmh5nc6zIsv6Xlg29sjBMshp1yAK3xiRyqqw7tIL6FTvyhaqsRTbxxRH03elpWeJBdvfYs2IgsGfWoOJ0V9gaT5pQww3mYLmbsSW+LzN2QzKQEU8HWCNGaWaS3aULCw/8wDSgAvvLe0IVAerKDOWL87dbiHyhWytih5DnXQAzMnMLEkuanMRbdt/sn3NCvCsGDJvZWKavAbQCkl9lLtnJwmI/v0Pf1Dtj2A/AECULf4cYe2xfSl1WFqSGqBz3+X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: infisical-universal-auth
      namespace: norriswu0-prod
