apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: norriswu0-db-superuser
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: norriswu0-db-superuser
    creationPolicy: Merge
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /norriswu0-db/SUPERUSER_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: norriswu0-db-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: norriswu0-db-app
    creationPolicy: Merge
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: playground-user
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /norriswu0-db/PLAYGROUND_USER_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: pgadmin-secrets
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /norriswu0-db/PGADMIN_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /norriswu0-db/PGADMIN_PASSWORD
