apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: playground-user
spec:
  name: playground-user
  ensure: present
  login: true
  passwordSecret:
    name: norriswu0-db-app
  cluster:
    name: norriswu0-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: playground
spec:
  name: playground
  owner: playground-user
  cluster:
    name: norriswu0-db
