apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: hermes-secrets
  data:
    - secretKey: DEEPSEEK_API_KEY
      remoteRef:
        key: /hermes/DEEPSEEK_API_KEY
    - secretKey: API_SERVER_KEY
      remoteRef:
        key: /hermes/API_SERVER_KEY
    - secretKey: HERMES_DASHBOARD_OIDC_ISSUER
      remoteRef:
        key: /hermes/HERMES_DASHBOARD_OIDC_ISSUER
    - secretKey: HERMES_DASHBOARD_OIDC_CLIENT_ID
      remoteRef:
        key: /hermes/HERMES_DASHBOARD_OIDC_CLIENT_ID
    - secretKey: DISCORD_ALLOWED_ROLES
      remoteRef:
        key: /hermes/DISCORD_ALLOWED_ROLES
