apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beaverhabit-secrets
  namespace: norriswu0
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: norriswu0-secret-store
    kind: SecretStore
  target:
    name: beaverhabit-secrets
  data:
    - secretKey: TRUSTED_LOCAL_EMAIL
      remoteRef:
        key: /beaverhabit/TRUSTED_LOCAL_EMAIL
