apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norriswu0-dev

resources:
  - ../../base

images:
  - name: ghcr.io/norriswu0/me
    newTag: 41e5e8b0fcbda171d75c3236b835681b545e9a20
