apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norriswu0-dev

resources:
  - ../../base

images:
  - name: ghcr.io/norriswu0/me
    newTag: 732ad448c0970c233e752d08e244f9a593db1588
