apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norriswu0-dev

resources:
  - ../../base

images:
  - name: ghcr.io/norriswu0/me
    newTag: cdf7298bca979709382532dae4e2c4b7111e89ec
