apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: norriswu0-tls-issuer-prod
spec:
  acme:
    email: me@norriswu.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: norriswu0-tls-issuer-prod-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secrets
              key: api-token
